# Generated by Django 3.0.7 on 2020-06-17 19:21

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('logo', models.ImageField(upload_to='logos/')),
                ('email', models.CharField(max_length=255)),
                ('gym', models.CharField(max_length=255)),
                ('forSale', models.IntegerField()),
								('notified', models.DateTimeField(auto_now=True, default=timezone.now))
            ],
        ),
    ]
