# Generated by Django 3.0.7 on 2020-09-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='notified',
            field=models.DateTimeField(auto_now=True),
						preserve_default=False
        ),
    ]
