# Generated by Django 3.0.7 on 2020-09-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200911_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='notified',
            field=models.DateTimeField(null=True),
        ),
    ]
