# Generated by Django 3.0.7 on 2020-09-11 18:28

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=items.models.get_upload_path),
        ),
    ]
